plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.solr:solr-solrj:9.10.1'
    implementation 'org.apache.solr:solr-core:9.10.1'
}

jar {
    archiveFileName = 'dynamic-facetting.jar'
}
